#!/usr/bin/env node
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(repoRoot, ".env");
const pemPath = path.join(repoRoot, "github-app.pem");

async function fileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function parseEnv(content) {
  const values = new Map();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    values.set(trimmed.slice(0, idx), trimmed.slice(idx + 1));
  }
  return values;
}

function serializeEnv(values) {
  const order = [
    "PORT",
    "DATABASE_URL",
    "REDIS_URL",
    "ANALYSIS_WORKER_CONCURRENCY",
    "GITHUB_TOKEN",
    "GITHUB_APP_ID",
    "GITHUB_APP_PRIVATE_KEY_PATH",
    "GITHUB_APP_WEBHOOK_SECRET",
    "PUBLIC_API_URL",
    "LLM_API_KEY",
    "LLM_BASE_URL",
    "LLM_MODEL",
    "LLM_MODEL_ARCHITECTURE_MODEL",
    "LLM_MODEL_RUNTIME_MODEL",
    "LLM_MODEL_DEVOPS_MODEL",
    "LLM_MODEL_SECURITY_MODEL",
    "LLM_MODEL_PLANNING_MODEL",
    "LLM_MODEL_CONSENSUS",
    "REPORT_SIGNING_SECRET",
  ];

  const lines = ["# CodeTruth OS — generated by npm run setup:env", ""];
  const written = new Set();

  for (const key of order) {
    if (!values.has(key)) continue;
    lines.push(`${key}=${values.get(key)}`);
    written.add(key);
  }

  for (const [key, value] of values) {
    if (written.has(key)) continue;
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  return `${lines.join("\n")}`;
}

async function ensureGitHubAppKey() {
  if (await fileExists(pemPath)) return pemPath;

  const { privateKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  await writeFile(pemPath, privateKey, "utf8");
  return pemPath;
}

async function main() {
  const existing = (await fileExists(envPath)) ? await readFile(envPath, "utf8") : "";
  const env = parseEnv(existing);

  env.set("PORT", env.get("PORT") ?? "4310");
  env.set("REDIS_URL", env.get("REDIS_URL") ?? "redis://localhost:6379");
  env.set("ANALYSIS_WORKER_CONCURRENCY", env.get("ANALYSIS_WORKER_CONCURRENCY") ?? "2");

  await ensureGitHubAppKey();
  env.set("GITHUB_APP_PRIVATE_KEY_PATH", "./github-app.pem");
  env.set("GITHUB_APP_ID", env.get("GITHUB_APP_ID") ?? "000000");
  env.set(
    "GITHUB_APP_WEBHOOK_SECRET",
    env.get("GITHUB_APP_WEBHOOK_SECRET") ?? randomBytes(24).toString("hex"),
  );

  const llmKey =
    env.get("LLM_API_KEY") ??
    process.env.LLM_API_KEY ??
    process.env.OPENAI_API_KEY ??
    "";
  if (llmKey) {
    env.set("LLM_API_KEY", llmKey);
  } else {
    env.delete("LLM_API_KEY");
  }

  env.set("LLM_BASE_URL", env.get("LLM_BASE_URL") ?? "https://api.openai.com/v1");
  env.set("LLM_MODEL", env.get("LLM_MODEL") ?? "gpt-4o-mini");
  env.set("LLM_MODEL_ARCHITECTURE_MODEL", env.get("LLM_MODEL_ARCHITECTURE_MODEL") ?? "gpt-4o-mini");
  env.set("LLM_MODEL_RUNTIME_MODEL", env.get("LLM_MODEL_RUNTIME_MODEL") ?? "gpt-4o");
  env.set("LLM_MODEL_DEVOPS_MODEL", env.get("LLM_MODEL_DEVOPS_MODEL") ?? "gpt-4o-mini");
  env.set("LLM_MODEL_SECURITY_MODEL", env.get("LLM_MODEL_SECURITY_MODEL") ?? "gpt-4o-mini");
  env.set("LLM_MODEL_PLANNING_MODEL", env.get("LLM_MODEL_PLANNING_MODEL") ?? "gpt-4o-mini");
  env.set("LLM_MODEL_CONSENSUS", env.get("LLM_MODEL_CONSENSUS") ?? "gpt-4o");

  env.set(
    "REPORT_SIGNING_SECRET",
    env.get("REPORT_SIGNING_SECRET") ?? randomBytes(32).toString("hex"),
  );

  await writeFile(envPath, serializeEnv(env), "utf8");

  console.log("Environment configured:");
  console.log(`  .env           → ${envPath}`);
  console.log(`  github-app.pem → ${pemPath}`);
  console.log(`  REDIS_URL      → ${env.get("REDIS_URL")}`);
  console.log(`  GitHub App     → ID ${env.get("GITHUB_APP_ID")} (replace 000000 with your App ID)`);
  console.log(`  LLM Council    → ${llmKey ? "enabled (API key set)" : "disabled — add LLM_API_KEY to .env"}`);
  console.log("");
  console.log("Next steps:");
  console.log("  1. npm run infra:up          # start Redis (+ Postgres optional)");
  console.log("  2. Add LLM_API_KEY to .env   # OpenAI or compatible provider");
  console.log("  3. Register GitHub App       # upload github-app.pem public key, set GITHUB_APP_ID");
  console.log("  4. npm run dev:full          # API + worker with all integrations");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});